---
title: "smart_map_bg_analysis"
author: ""
date: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
hl_deltas <- readRDS(here('./data/mitre/working/logistic_regressions/high_low_deltas.RDS'))
```


```{r}
tract_bg_hl <- hl_deltas %>%
    mutate(tract_bg = stringr::str_extract(hl_deltas$GEOID, '\\d{7}$')) %>%
    .$tract_bg

base_dir <- './data/mitre/working/imputationAndResamplingResults/sqrtHINCP_RMSP_householdSize_singleParent_snKid_militaryService_unmarriedPartner_multiGenHouse/'

ss_resamples_f <- sprintf('%s/bg_%s/resamples.csv', base_dir, tract_bg_hl)

ss_resamples <- purrr::map(
    ss_resamples_f,
    read.csv, stringsAsFactors = FALSE
)

ss_resamples[[1]]
ss_resamples_f[[1]]

```

```{r}
ss_resamples[[1]][1:3]
```

```{r}
sapply(ss_resamples, dim) / 8
```



```{r}
source("./R/00-simulateArlFunctions.R")
library(data.table)
path = "./data/mitre/working/imputationAndResamplingResults/sqrtHINCP_RMSP_householdSize_singleParent_snKid_militaryService_unmarriedPartner_multiGenHouse/"

simulation = getResampleByIndex(path, 5)

# sims <- lapply(1:10, function(x){
#   df <- getResampleByIndex(path, x)
#   df$sample <- x
#   return(df)
# })
```

```{r}
hl_deltas %>%
    mutate(tbg = paste0(as.character(TRACTCE), as.character(BLKGRPCE)))
```


```{r}
simulation

sim_1_mean <- simulation %>% 
    dplyr::group_by(blockGroup) %>%
    summarize(rmsp_mean = mean(RMSP, na.rm = TRUE),
              householdsize_mean = mean(householdSize, na.rm = TRUE),
              militaryservice_mean = mean(militaryService, na.rm = TRUE),
              multiGenHouse_mean = mean(multiGenHouse, na.rm = TRUE),
              singleParent_mean = mean(singleParent, na.rm = TRUE),
              snKid_mean = mean(snKid, na.rm = TRUE),
              sqrtHINCP_mean = mean(sqrtHINCP, na.rm = TRUE),
              unmarriedPartner_mean = mean(unmarriedPartner, na.rm = TRUE)
    )



ref <- sim_1_mean %>%
    filter(!blockGroup %in% c("1028013", "1022001", "1028022", "1025003", "1031003")) %>%
    purrr::map_df(mean) %>%
    mutate(blockGroup = 'reference')


high <- sim_1_mean %>%
    filter(blockGroup %in% c("1028013", "1022001", "1028022", "1025003", "1031003")) %>%
    rbind(ref)

```

```{r}
df <- tidyr::gather(high, key = 'key', value = 'value', rmsp_mean:unmarriedPartner_mean)
```

```{r}
p_delta_selected_comparison <- ggplot(df) + geom_bar(aes(x = blockGroup, y = value), stat = 'identity') +
    facet_wrap(~key, scales = 'free') +
    theme_minimal() +
    ggtitle('Comparing "high" block groups with county averages') +
    xlab('Tract + Block Group') +
    ylab('Value') +
    coord_flip()
ggsave(here('./output/smart_analysis/plots/p_delta_selected_comparison.pdf'), width = 8, height = 5, units = 'in', dpi = 300)
p_delta_selected_comparison
```

