---
title: "Smart Analysis"
author: "Daniel Chen"
date: "9/7/2018"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 8, fig.height = 5 # golden ratio
                      )

# disable scientific notation
options(scipen = 999)
```

```{r}
smart_coefficients <- readRDS(here('data/mitre/final/logistic_regressions/coefficients.RDS'))
smart_deviances <- readRDS(here('data/mitre/final/logistic_regressions/deviance.RDS'))
fit0 <- readRDS(here('./data/mitre/working/logistic_regressions/example_fit0.RDS'))
fit1 <- readRDS(here('./data/mitre/working/logistic_regressions/example_fit1.RDS'))
```

```{r}
library(broom)
library(dplyr)
library(tidyr)
library(ggplot2)

ggplot2::theme_set(theme_bw())
```

```{r}
# get order of coefficient names
coef_names <- tidy(fit1)$term
smart_coefficients <- tibble::as_tibble(t(smart_coefficients))
names(smart_coefficients) <- coef_names
```

```{r}
smart_coefficients$sim_num <- 1:nrow(smart_coefficients)

tidy_coefs <- smart_coefficients %>%
  tidyr::gather(key = 'variable',
         value = 'coefficient',
         `(Intercept)`:milWoman) %>%
  dplyr::mutate(or = exp(coefficient))
```

# Logistic Regression

## Coefficients

Jittered scatter plot of the coefficients from simulation runs

```{r}
ggplot(tidy_coefs) +
  geom_jitter(aes(x = coefficient, y = as.factor(variable)), alpha = .5) +
  ggtitle('Coefficients for the Simulation Runs')
```

```{r}
ggplot(tidy_coefs) +
  geom_histogram(aes(x = coefficient)) +
  facet_wrap(~as.factor(variable)) +
  ggtitle('Distribution of simulated coefficients')
```

## "peaky"

```{r}
ggplot(dplyr::filter(tidy_coefs, variable == 'DRUGrate')) +
  geom_histogram(aes(x = coefficient)) +
  ggtitle('Distribution of DRUGrate')
```


```{r}
ggplot(dplyr::filter(tidy_coefs, variable == 'householdSize')) +
  geom_histogram(aes(x = coefficient)) +
  ggtitle('Distribution of householdSize')
```


```{r}
ggplot(dplyr::filter(tidy_coefs, variable == 'medInc')) +
  geom_histogram(aes(x = coefficient)) +
  ggtitle('Distribution of medInc')
```


```{r}
ggplot(dplyr::filter(tidy_coefs, variable == 'RMSP')) +
  geom_histogram(aes(x = coefficient)) +
  ggtitle('Distribution of RMSP')
```


## Odds Ratios

```{r}
g <- ggplot(tidy_coefs) +
  geom_jitter(aes(x = or, y = as.factor(variable)), alpha = .5)

g +  ggtitle('ORs for the Simulation Runs')
```

```{r}
g +
  xlim(0, 5)  +
  ggtitle('Truncated ORs')
```

Disribution of ORs

```{r}
ggplot(tidy_coefs) +
  geom_histogram(aes(x = or)) +
  facet_wrap(~variable) +
  ggtitle('Distrubution of ORs')
```



```{r}
ggplot(dplyr::filter(tidy_coefs, or < 5)) +
  geom_histogram(aes(x = or), bins = 50) +
  facet_wrap(~variable) +
  ggtitle('Truncated Distrubutions')
```

